[package]
name = "tsh_bindings"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.145"
tree-sitter = "0.26.3"
tree-sitter-highlight = "0.26.3"
tree-sitter-ocaml = "0.24.2"
